server:
  max-http-request-header-size: 1MB
spring:
  application:
    name: marker-data
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 105MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    deserialization:
      fail-on-unknown-properties: false
  datasource:
    url: jdbc:mysql://192.168.3.108:3306/17oa?useUnicode=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: equipl123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 10
      maximumPoolSize: 100

mybatis-plus:
  # mapper.xml文件扫描地址
  mapper-locations: classpath:/mappers/*.xml
  global-config:
    banner: false
    db-config:
      # 自增
      id-type: assign_id
      # 大写转下划线
      table-underline: true
      # 插入以及更新策略
      insert-strategy: not_null
      update-strategy: not_empty
      # 未删除值
      logic-not-delete-value: 1
      # 已删除值
      logic-delete-value: 0
      # 逻辑删除字段
      logic-delete-field: deleted
  configuration:
    # 数据库字段自动转成实体类字段
    map-underscore-to-camel-case: true
    cache-enabled: false
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl